#!/bin/sh

set -e

PKG=yavdr-desktop

if [ "$1" = remove ] ; then
	DESKTOP_SESSION=gnome-fallback

        FILES="/etc/pulse/default.pa"

        for f in $FILES
        do
                [ -L $f ] && rm $f
                dpkg-divert --remove --package ${PKG} --rename \
                        --divert $f.distrib $f
        done

        sed -i -e "/^$DESKTOP_SESSION\$/d" /etc/upstart-xsessions
fi

#DEBHELPER#

exit 0
